version: '3'

services:
  nginx:
    image: moriorgames/sf6.3-nginx
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile-nginx
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - .:/app
    depends_on:
      - app

  app:
    image: moriorgames/sf6.3-app
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile-php
    container_name: app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dev
    container_name: db
