version: '3'

services:
  app:
    image: moriorgames/sf6.3-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dev
    container_name: db
