version: '3'

services:
  app-test:
    image: moriorgames/sf6.3-app
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile-php-xdebug
    container_name: app_test
    volumes:
      - .:/app
    depends_on:
      - db-test

  db-test:
    image: mariadb
    environment:
      MYSQL_DATABASE: dev_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
      MYSQL_TCP_PORT: 3306
    container_name: db_test
    ports:
    - 3306:3306
    expose:
      - 3306
