FROM php:8.1-fpm

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends

RUN docker-php-ext-install pdo pdo_mysql

COPY . /app
RUN php phars/composer.phar install

EXPOSE 9000

CMD ["php-fpm"]
