FROM php:8.1-fpm

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends

RUN docker-php-ext-install pdo pdo_mysql

RUN pecl install xdebug-3.1.5
RUN docker-php-ext-enable xdebug
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.log=/var/www/html/xdebug/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini

COPY . /app
RUN php phars/composer.phar install

EXPOSE 9000

CMD ["php-fpm"]
