FROM nginx

# Eliminar la configuración predeterminada de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar tu archivo de configuración personalizado de Nginx
COPY docker/nginx/symfony.conf /etc/nginx/conf.d/

# Exponer el puerto 80 para que se pueda acceder a Nginx
EXPOSE 80

# Definir el comando de inicio para Nginx
CMD ["nginx", "-g", "daemon off;"]
