parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/BoundedContext/DependencyInjection/'
            - '../src/BoundedContext/Entity/'
            - '../src/Kernel.php'
